### ISSUE TITLE
[suggestion] to add doc about git hook which would not depend upon 3-rd party tool

### ISSUE THREAD

**Issue by kopach** [folke/devmoji#87]
Hi. In my project we do use conventional commits, but we don't use husky or Yorkie, also we don't want to force people to use emojis in commits. However, personally, I like putting emojis into my commits and I want it to be automated. Therefore, I've added `devmoji` into my .git/hooks/ manually. Here is info on how I have this done. In the root of project, run:

```sh
cp .git/hooks/prepare-commit-msg.sample .git/hooks/prepare-commit-msg # note, it's important to copy this to make sure file is executable
echo "#\!/bin/sh\n\nCOMMIT_MSG_FILE=\$1\nCOMMIT_MSG=\$(cat \$COMMIT_MSG_FILE)\n\necho \"\${COMMIT_MSG}\" | devmoji > \$1" > .git/hooks/prepare-commit-msg
```

Would be great to have this added to the README of the project. Thans

**Comment by folke** [comment]
Thank you for the suggestion!
I've added a link to this issue from the docs.

Fixed in https://github.com/folke/devmoji/commit/8f7b36ab0ec7e0623f0e0a597d166749d250912e

**Comment by vhscom** [comment]
I'm guessing OP was running macOS. On Linux you need to use `echo -e` in order to enable interpretation of backslash escapes. Then their hook works great. Another good reason not to use Husky is it falls apart when you try and perform an interactive rebase and that's extremely frustrating when you're at the finish line.

**Comment by vhscom** [comment]
I'm guessing OP was running macOS. On Linux you need to use `echo -e` in order to enable interpolation of backslash escapes. Then their hook works great. Another good reason not to use Husky is it falls apart when you try and perform an interactive rebase and that's frustrating when you're right at the finish line.

**Comment by arantebw** [comment]
I agree with @vhscom, it will fail on Linux if `echo` does not have the `-e` option. So,

`echo -e "#\!/bin/sh\n\nCOMMIT_MSG_FILE=\$1\nCOMMIT_MSG=\$(cat \$COMMIT_MSG_FILE)\n\necho \"\${COMMIT_MSG}\" | devmoji > \$1" > .git/hooks/prepare-commit-msg`
